$pkg_name="effortless-a2-profile-test"
$pkg_origin="chef"
$pkg_version="0.1.0"
$pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
$pkg_license=("Apache-2.0")
$pkg_build_deps=@("stuartpreston/inspec")
$pkg_deps=@("stuartpreston/inspec")
$pkg_description="Effortless Windows Audit"
$pkg_scaffolding="thelunaticscripter/scaffolding-chef-inspec"
$scaffolding_automate_server_url = "$env:AUTOMATE_SERVER_URL"
$scaffolding_automate_user = "$env:AUTOMATE_USER"
$scaffolding_automate_token = "$env:AUTOMATE_TOKEN"